spring:
  application:
    name: client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  activemq:
    broker-url: tcp://localhost:61617
  jms:
    pub-sub-domain: true
server:
  port: 8887

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.client.model